# Generated by Django 5.2.6 on 2025-10-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockgeneraljob',
            name='closure',
            field=models.BooleanField(default=False),
        ),
    ]
