# Generated by Django 5.2.6 on 2025-10-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_qualif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecv',
            name='resume_file',
            field=models.FileField(default='documents/default.txt', upload_to='documents/'),
        ),
    ]
