# Generated by Django 5.2.6 on 2025-10-13 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_qualif', '0002_resumecv_resume_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecv',
            name='adress_user',
            field=models.CharField(default='', max_length=50, verbose_name='Informe o seu Endereço completo'),
        ),
        migrations.AlterField(
            model_name='resumecv',
            name='celphone',
            field=models.CharField(max_length=20, verbose_name='Telefone de contato'),
        ),
        migrations.AlterField(
            model_name='resumecv',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Cidade de Residencia'),
        ),
        migrations.AlterField(
            model_name='resumecv',
            name='courses',
            field=models.TextField(blank=True, null=True, verbose_name='Quais as tecnologias que vc conhece ?'),
        ),
        migrations.AlterField(
            model_name='resumecv',
            name='email',
            field=models.EmailField(max_length=35, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='resumecv',
            name='experiences',
            field=models.TextField(blank=True, null=True, verbose_name='Informe suas Experiências anteriores'),
        ),
        migrations.AlterField(
            model_name='resumecv',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='O curriculum é valido ?'),
        ),
        migrations.AlterField(
            model_name='resumecv',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='resumecv',
            name='qualifications',
            field=models.TextField(blank=True, null=True, verbose_name='Informe sua Escolaridade'),
        ),
        migrations.AlterField(
            model_name='resumecv',
            name='resume_file',
            field=models.FileField(default='documents/default.txt', upload_to='documents/', verbose_name='Realize o upload do seu Curriculum Vitae'),
        ),
        migrations.AlterField(
            model_name='resumecv',
            name='state',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='resumecv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nome do usuário'),
        ),
    ]
