# Generated by Django 5.1.6 on 2025-08-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empregos',
            name='user',
        ),
    ]
