# Generated by Django 5.1.6 on 2025-09-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_empregos_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empregos',
            name='type',
        ),
        migrations.AddField(
            model_name='empregos',
            name='type_job',
            field=models.CharField(choices=[('1', 'CLT - 8  horas'), ('2', 'Consultoria - 8 horas')], default='1', max_length=10),
        ),
    ]
