# Generated by Django 5.2.3 on 2025-09-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_empregos_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empregos',
            name='type',
        ),
    ]
