# Generated by Django 5.2.3 on 2025-09-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_empregos_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregos',
            name='type_job',
            field=models.CharField(choices=[('1', 'CLT - 8  horas'), ('2', 'Consultoria - 8 horas')], default='1', max_length=10),
        ),
    ]
