# Generated by Django 5.2.4 on 2025-09-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_empregos_type_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregos',
            name='last_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='type_job',
            field=models.CharField(choices=[('0', 'Selecione uma opção'), ('1', 'CLT - 8  horas'), ('2', 'Consultoria - 8 horas')], default='0', max_length=10),
        ),
    ]
