# Generated by Django 5.2.4 on 2025-09-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_empregos_type_empregos_type_job'),
        ('produtos', '0004_empregos_type_job'),
    ]

    operations = [
    ]
