# Generated by Django 5.2.4 on 2025-09-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_empregos_last_date_alter_empregos_type_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empregos',
            old_name='type_job',
            new_name='job_option',
        ),
        migrations.AlterField(
            model_name='empregos',
            name='description',
            field=models.TextField(verbose_name='Descrição da vaga'),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Título da vaga'),
        ),
    ]
