# Generated by Django 5.2.6 on 2025-10-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_empregos_filled_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyDefendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(help_text='Informe a identificação da tag', max_length=100, unique=True, verbose_name='Identificacao')),
                ('descricao', models.TextField(default='N/A', help_text='Informe a descrição da categoria', verbose_name='Descrição')),
            ],
        ),
        migrations.AlterModelOptions(
            name='empregos',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='empregos',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Atuação da Vaga'),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='company_description',
            field=models.CharField(max_length=300, verbose_name='Atuação da Empresa Solicitante'),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Empresa Solicitante'),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='filled',
            field=models.BooleanField(default=True, verbose_name='Vaga está ativa ?'),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='job_option',
            field=models.CharField(choices=[('0', 'Selecione uma opção'), ('1', 'CLT - 8  horas'), ('2', 'Consultoria - 8 horas')], default='0', max_length=10, verbose_name='Tipo de contratação'),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='last_date',
            field=models.DateTimeField(verbose_name='Data de Postagem da Vaga'),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Atuação da Vaga/Remoto ou Local'),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='salary',
            field=models.IntegerField(blank=True, default=0, verbose_name='Salario proposto ?'),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='vacancy',
            field=models.IntegerField(default=1, verbose_name='Quantidade de Vagas propostas ?'),
        ),
        migrations.AlterField(
            model_name='empregos',
            name='website',
            field=models.CharField(default='', max_length=100, verbose_name='Web Site da Empresa Solicitante'),
        ),
        migrations.AddField(
            model_name='empregos',
            name='specialtydefendant',
            field=models.ManyToManyField(related_name='specialty_defendant', to='produtos.specialtydefendant'),
        ),
    ]
