# Generated by Django 5.2.6 on 2025-10-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_specialtydefendant_alter_empregos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtydefendant',
            name='descricao',
            field=models.TextField(max_length=200, verbose_name='Descrição da Especialidade'),
        ),
        migrations.AlterField(
            model_name='specialtydefendant',
            name='identificacao',
            field=models.CharField(max_length=100, verbose_name='Título da Especialidade'),
        ),
    ]
