# Generated by Django 5.2.6 on 2025-10-09 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_empregos_options_appliedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='approved',
        ),
    ]
