# Generated by Django 5.2.6 on 2025-10-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_remove_appliedjob_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='observation',
            field=models.TextField(max_length=300, verbose_name='Crei uma carta de Apresentação'),
        ),
    ]
