# Generated by Django 5.2.6 on 2025-10-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboarforuser',
            name='approvedselection',
            field=models.BooleanField(default=False),
        ),
    ]
