# Generated by Django 5.2.6 on 2025-10-09 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0011_remove_appliedjob_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRdecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_observation', models.TextField(max_length=300, verbose_name='Descrição da vaga')),
                ('rh_decision', models.CharField(choices=[('0', 'Selecione uma opção'), ('1', 'Aprovado'), ('2', 'Rejeitado')], default='0', max_length=10, null=True, verbose_name='Decisão da Aprovação')),
                ('rh_observation', models.TextField(max_length=300, null=True, verbose_name='Descrição da vaga')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.empregos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
