# Generated by Django 5.2.6 on 2025-10-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrdecision',
            name='candidate_observation',
            field=models.TextField(max_length=300, null=True, verbose_name='Descrição da vaga'),
        ),
    ]
