# Generated by Django 5.2.6 on 2025-10-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhmanager', '0002_alter_hrdecision_candidate_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrdecision',
            name='candidate_observation',
            field=models.TextField(max_length=300, null=True, verbose_name='Descrição do Canditatos'),
        ),
        migrations.AlterField(
            model_name='hrdecision',
            name='rh_observation',
            field=models.TextField(max_length=300, null=True, verbose_name='Descrição'),
        ),
    ]
